version: "3"
tasks:
  genproto: >
    protoc\
        --go_out=.\
        --go_opt=module=$(task gomod)\
        --go-grpc_out=.\
        --go-grpc_opt=module=$(task gomod)\
        --grpc-gateway_out=./pkg/api/grpc/TxOuts_V1\
        --grpc-gateway_opt paths=source_relative\
        -Iapi/grpc/proto\
        api/grpc/proto/*.proto
  genswagger: >
    protoc\
        --openapiv2_out=./api/http\
        --openapiv2_opt=output_format=yaml\
        -Iapi/grpc/proto\
        api/grpc/proto/*.proto
  gomod: go mod edit -json | jq -r '.Module.Path'
  dockerbuild: docker build -t bitcoin-utxo-indexer -f Dockerfile .
  build: mkdir -p ./bin && go build -o ./bin ./...
