version: '3'
tasks:
  genproto: >
    protoc\
        --go_out=.\
        --go_opt=module=$(task gomod)\
        --go-grpc_out=.\
        --go-grpc_opt=module=$(task gomod)\
        api/grpc/proto/*.proto

  gomod: go mod edit -json | jq -r '.Module.Path'
  dockerbuild: docker build -t bitcoin-utxo-indexer -f Dockerfile .


