// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.12.4
// source: api/grpc/proto/utxo.proto

package UTXO

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetByAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Account address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetByAddressRequest) Reset() {
	*x = GetByAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_utxo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAddressRequest) ProtoMessage() {}

func (x *GetByAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_utxo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAddressRequest.ProtoReflect.Descriptor instead.
func (*GetByAddressRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_utxo_proto_rawDescGZIP(), []int{0}
}

func (x *GetByAddressRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetByAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnspentOutputs []*UnspentTransactionOutput `protobuf:"bytes,1,rep,name=unspent_outputs,json=unspentOutputs,proto3" json:"unspent_outputs,omitempty"`
}

func (x *GetByAddressResponse) Reset() {
	*x = GetByAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_utxo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetByAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetByAddressResponse) ProtoMessage() {}

func (x *GetByAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_utxo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetByAddressResponse.ProtoReflect.Descriptor instead.
func (*GetByAddressResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_utxo_proto_rawDescGZIP(), []int{1}
}

func (x *GetByAddressResponse) GetUnspentOutputs() []*UnspentTransactionOutput {
	if x != nil {
		return x.UnspentOutputs
	}
	return nil
}

type UnspentTransactionOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UnspentTransactionOutput) Reset() {
	*x = UnspentTransactionOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_proto_utxo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UnspentTransactionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnspentTransactionOutput) ProtoMessage() {}

func (x *UnspentTransactionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_proto_utxo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnspentTransactionOutput.ProtoReflect.Descriptor instead.
func (*UnspentTransactionOutput) Descriptor() ([]byte, []int) {
	return file_api_grpc_proto_utxo_proto_rawDescGZIP(), []int{2}
}

var File_api_grpc_proto_utxo_proto protoreflect.FileDescriptor

var file_api_grpc_proto_utxo_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x75, 0x74, 0x78, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2f, 0x0a, 0x13, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x5a, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x0f, 0x75, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x5f,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e,
	0x55, 0x6e, 0x73, 0x70, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x52, 0x0e, 0x75, 0x6e, 0x73, 0x70, 0x65, 0x6e,
	0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x73, 0x22, 0x1a, 0x0a, 0x18, 0x55, 0x6e, 0x73, 0x70,
	0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x32, 0x43, 0x0a, 0x04, 0x55, 0x54, 0x58, 0x4f, 0x12, 0x3b, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x15, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x79, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x36, 0x5a, 0x34, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x69, 0x72, 0x69, 0x63, 0x63, 0x2f, 0x62,
	0x74, 0x63, 0x2d, 0x75, 0x74, 0x78, 0x6f, 0x2d, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x72, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x55, 0x54, 0x58,
	0x4f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_proto_utxo_proto_rawDescOnce sync.Once
	file_api_grpc_proto_utxo_proto_rawDescData = file_api_grpc_proto_utxo_proto_rawDesc
)

func file_api_grpc_proto_utxo_proto_rawDescGZIP() []byte {
	file_api_grpc_proto_utxo_proto_rawDescOnce.Do(func() {
		file_api_grpc_proto_utxo_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_proto_utxo_proto_rawDescData)
	})
	return file_api_grpc_proto_utxo_proto_rawDescData
}

var file_api_grpc_proto_utxo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_grpc_proto_utxo_proto_goTypes = []interface{}{
	(*GetByAddressRequest)(nil),      // 0: GetByAddressRequest
	(*GetByAddressResponse)(nil),     // 1: GetByAddressResponse
	(*UnspentTransactionOutput)(nil), // 2: UnspentTransactionOutput
}
var file_api_grpc_proto_utxo_proto_depIdxs = []int32{
	2, // 0: GetByAddressResponse.unspent_outputs:type_name -> UnspentTransactionOutput
	0, // 1: UTXO.GetByAddress:input_type -> GetByAddressRequest
	1, // 2: UTXO.GetByAddress:output_type -> GetByAddressResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_proto_utxo_proto_init() }
func file_api_grpc_proto_utxo_proto_init() {
	if File_api_grpc_proto_utxo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_proto_utxo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_utxo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetByAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_proto_utxo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UnspentTransactionOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_proto_utxo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_proto_utxo_proto_goTypes,
		DependencyIndexes: file_api_grpc_proto_utxo_proto_depIdxs,
		MessageInfos:      file_api_grpc_proto_utxo_proto_msgTypes,
	}.Build()
	File_api_grpc_proto_utxo_proto = out.File
	file_api_grpc_proto_utxo_proto_rawDesc = nil
	file_api_grpc_proto_utxo_proto_goTypes = nil
	file_api_grpc_proto_utxo_proto_depIdxs = nil
}
